export const links = [
  { id: 1, url: "/", name: "Home" },
  { id: 2, url: "/characters", name: "Characters" },
  { id: 3, url: "/combos", name: "Combos" },
  { id: 4, url: "/framedata", name: "Frame Data" },
];

export const characters = [
  {
    id: 1,
    name: "Luke",
    img: "./src/images/sf6 designed character cards/luke.png",
    abilities: [""],
    href: "/character/luke",
  },
  {
    id: 2,
    name: "Jaime",
    img: "/src/images/sf6 designed character cards/jaime.png",
    abilities: [""],
    href: "/character/jamie",
  },
  {
    id: 3,
    name: "Manon",
    img: "./src/images/sf6 designed character cards/Manon.png",
    abilities: [""],
    href: "/character/manon/",
  },
  {
    id: 4,
    name: "Kimberly",
    img: "./src/images/sf6 designed character cards/kimberly.png",
    abilities: [""],
    href: "/character/kimberly/",
  },
  {
    id: 5,
    name: "Marisa",
    img: "./src/images/sf6 designed character cards/Marisa.png",
    abilities: [""],
    href: "/character/marisa/",
  },
  {
    id: 6,
    name: "Lily",
    img: "./src/images/sf6 designed character cards/lily.png",
    abilities: [""],
    href: "/character/lily/",
  },
  {
    id: 7,
    name: "Jp",
    img: "./src/images/sf6 designed character cards/jp.png",
    abilities: [""],
    href: "/character/jp/",
  },
  {
    id: 8,
    name: "Juri",
    img: "./src/images/sf6 designed character cards/juri.png",
    abilities: [""],
    href: "/character/juri/",
  },
  {
    id: 9,
    name: "Dee Jay",
    img: "./src/images/sf6 designed character cards/Deejay.png",
    abilities: [""],
    href: "/character/deejay/",
  },
  {
    id: 10,
    name: "Cammy",
    img: "./src/images/sf6 designed character cards/Cammy.png",
    abilities: [""],
    href: "/character/cammy/",
  },
  {
    id: 11,
    name: "Ryu",
    img: "./src/images/sf6 designed character cards/ryu.png",
    abilities: [""],
    href: "/character/ryu/",
  },
  {
    id: 12,
    name: "Chun-Li",
    img: "./src/images/sf6 designed character cards/ChunLi.png",
    abilities: [""],
    href: "/character/chunli/",
  },
  {
    id: 13,
    name: "Zangief",
    img: "./src/images/sf6 designed character cards/Zangief.png",
    abilities: [""],
    href: "/character/zangief/",
  },
  {
    id: 14,
    name: "Dhalsim",
    img: "./src/images/sf6 designed character cards/Dhalsim.png",
    abilities: [""],
    href: "/character/dhalsim/",
  },
  {
    id: 15,
    name: "Rashid",
    img: "./src/images/sf6 designed character cards/Rashid.png",
    abilities: [""],
    href: "/character/rashid/",
  },
  {
    id: 16,
    name: "Aki",
    img: "./src/images/sf6 designed character cards/Aki.png",
    abilities: [""],
    href: "/character/aki/",
  },
  {
    id: 17,
    name: "Ed",
    img: "./src/images/sf6 designed character cards/ED.png",
    abilities: [""],
    href: "/character/ed/",
  },
  {
    id: 18,
    name: "Akuma",
    img: "./src/images/sf6 designed character cards/akuma.png",
    abilities: [""],
    href: "/character/akuma/",
  },
  {
    id: 19,
    name: "Elena",
    img: "./src/images/sf6 designed character cards/elena.png",
    abilities: [""],
    href: "/character/elena",
  },
  {
    id: 20,
    name: "M. Bison",
    img: "./src/images/sf6 designed character cards/m.bsion.png",
    abilities: [""],
    href: "/character/m.bison",
  },
  {
    id: 21,
    name: "Terry Bogard",
    img: "./src/images/sf6 designed character cards/Terry.png",
    abilities: [""],
    href: "/character/terry/",
  },
  {
    id: 22,
    name: "Mai Shiranui",
    img: "./src/images/sf6 designed character cards/mai.png",
    abilities: [""],
    href: "/character/mai-shiraui/",
  },
];

export const SocialLinks = [
  {
    id: 1,
    icon: "",
    href: "https://github.com/AndresFritsche",
    text: "github",
  },
];
